### ISSUE TITLE
This addon make LiveClick Extention not working properly

### ISSUE THREAD

**Issue by leomate** [JustOff/greedy-cache#1]
My configurations : 
Windows 10 x64
Palemoon 27.1 x64
[Liveclick 1.0.0.1-signed ](https://addons.mozilla.org/en-US/firefox/addon/liveclick/versions/1.0.0.1-signed)
Greedy Cache 1.1.2

When i enable greedy cache addon it seem everything is normal until i close the browser and open again the liveclick extentions not working until i disable greedycache and reopen the browser.

**Comment by JustOff** [comment]
It's unclear from your report what kind of problem you have with Liveclick, but probably it just incompatible with Greedy Cache.

**Comment by leomate** [comment]
Sorry for unclear message, i forgot to attach the pictures
![greedycache problem](https://cloud.githubusercontent.com/assets/24457355/22881205/185f9d34-f218-11e6-8681-71da0070045f.png)

Well if it isn't compatible, why it worked when it enable without restart  after disable and restart browser.

**Comment by JustOff** [comment]
Resolved in [1.1.3](https://github.com/JustOff/greedy-cache/releases/tag/1.1.3).
