### ISSUE TITLE
Support for basilisk

### ISSUE THREAD

**Issue by Felipefpl** [JustOff/greedy-cache#2]
Hi, your extension might be what i need since i have dialup here but it just supports pale moon, please add support for latest versions of basilisk, i mean versions because the last version isnt always the best one, in my case i didnt get it because it doesnt offer anything cool for me.

Thank you for your work with this, if this works here it'll likely work wonders with facebook (bloated site from hell) :)

**Comment by JustOff** [comment]
Sorry, I'm not going to support Basilisk officially, but you can try to install GC using [Serpent Tester Tool](https://github.com/Nebula-Mechanica/serpent-tester-tool).

**Comment by Felipefpl** [comment]
1st i wanna say thank you for indicating serpent to me, it did the job well and i could install greedy cache here without problems.

2nd - HONESTLY, i hope this work of yours may go not as an extension but as code itself inside basilisk/pale moon. Really, the way both deal with cache sucks just like with opera 12, cache is good on both if you use the browsers on a daily basis, if you stop using the computer for several days and use it again it's like you have to download a lot of stuff you have already in the cache.....

3rd - you should have a link to serpent in your site for greedy cache. ;)
